#! /bin/sh
# /etc/init.d/electronicLock

# The following part always gets executed.

# The following part carries out specific functions depending on arguments.
case "$1" in
  start)
    echo "Starting ElectronicLock"
	nohup /home/rohan/repos/ElectronicLock/ElectronicLock.py > /home/rohan/repos/ElectronicLock/lock.log &
    ;;
  *)
    echo "Usage: /etc/init.d/electronicLock {start}"
    exit 1
    ;;
esac

exit 0
